import type { ElementAsset } from "../element.types";
import { svg } from "./svg-helper";

export const BASIC_SHAPES_ELEMENTS: readonly ElementAsset[] = [
  {
    id: "basic-rectangle",
    name: "Rectangle",
    category: "Basic shapes",
    tags: ["box", "square", "block", "frame", "shape"],
    svg: svg('<rect x="8" y="18" width="84" height="64" fill="none" stroke="#2563eb" stroke-width="5"/>'),
    defaultSize: { width: 120, height: 92.09 },
    geometryBounds: { x: 8, y: 18, width: 84, height: 64 },
    insertion: { kind: "shape", shapeKind: "rectangle" },
    favourite: false,
    recent: false,
  },
  {
    id: "basic-square",
    name: "Square",
    category: "Basic shapes",
    tags: ["box", "square", "block", "frame", "shape"],
    svg: svg('<rect x="8" y="8" width="84" height="84" fill="none" stroke="#2563eb" stroke-width="5"/>'),
    defaultSize: { width: 96, height: 96 },
    geometryBounds: { x: 8, y: 8, width: 84, height: 84 },
    insertion: { kind: "shape", shapeKind: "rectangle" },
    favourite: false,
    recent: false,
  },
  {
    id: "basic-rounded-rectangle",
    name: "Rounded Rectangle",
    category: "Basic shapes",
    tags: ["box", "card", "button", "round", "pill", "container"],
    svg: svg('<rect x="8" y="18" width="84" height="64" rx="14" fill="none" stroke="#2563eb" stroke-width="5"/>'),
    defaultSize: { width: 120, height: 92.09 },
    geometryBounds: { x: 8, y: 18, width: 84, height: 64 },
    insertion: { kind: "shape", shapeKind: "roundedRectangle" },
    favourite: false,
    recent: false,
  },
  {
    id: "basic-circle",
    name: "Circle",
    category: "Basic shapes",
    tags: ["round", "ellipse", "dot", "badge", "ring", "disc"],
    svg: svg('<circle cx="50" cy="50" r="41" fill="none" stroke="#2563eb" stroke-width="5"/>'),
    defaultSize: { width: 96, height: 96 },
    geometryBounds: { x: 9, y: 9, width: 82, height: 82 },
    insertion: { kind: "shape", shapeKind: "circle" },
    favourite: false,
    recent: false,
  },
  {
    id: "basic-triangle",
    name: "Triangle",
    category: "Basic shapes",
    tags: ["shape", "three sides", "play", "delta", "pyramid"],
    svg: svg('<path d="M50 8 93 89H7Z" fill="none" stroke="#2563eb" stroke-width="5" stroke-linejoin="round"/>'),
    defaultSize: { width: 100, height: 94.32 },
    geometryBounds: { x: 7, y: 8, width: 86, height: 81 },
    insertion: { kind: "shape", shapeKind: "triangle" },
    favourite: false,
    recent: false,
  },
  {
    id: "basic-diamond",
    name: "Diamond",
    category: "Basic shapes",
    tags: ["rhombus", "gem", "rotate", "crystal", "card"],
    svg: svg('<path d="M50 6 94 50 50 94 6 50Z" fill="none" stroke="#2563eb" stroke-width="5" stroke-linejoin="round"/>'),
    defaultSize: { width: 96, height: 96 },
    geometryBounds: { x: 6, y: 6, width: 88, height: 88 },
    insertion: { kind: "graphic" },
    colourMode: "fill-and-stroke",
    favourite: false,
    recent: false,
  },
  {
    id: "basic-hexagon",
    name: "Hexagon",
    category: "Basic shapes",
    tags: ["polygon", "6 sides", "honeycomb", "geometry", "nut"],
    svg: svg('<path d="M25 8H75L96 50L75 92H25L4 50Z" fill="none" stroke="#2563eb" stroke-width="5" stroke-linejoin="round"/>'),
    defaultSize: { width: 104, height: 95.42 },
    geometryBounds: { x: 4, y: 8, width: 92, height: 84 },
    insertion: { kind: "graphic" },
    colourMode: "fill-and-stroke",
    favourite: false,
    recent: false,
  },
  {
    id: "basic-octagon",
    name: "Octagon",
    category: "Basic shapes",
    tags: ["stop sign", "polygon", "8 sides", "badge"],
    svg: svg('<path d="M30 6H70L94 30V70L70 94H30L6 70V30Z" fill="none" stroke="#2563eb" stroke-width="5" stroke-linejoin="round"/>'),
    defaultSize: { width: 96, height: 96 },
    geometryBounds: { x: 6, y: 6, width: 88, height: 88 },
    insertion: { kind: "graphic" },
    colourMode: "fill-and-stroke",
    favourite: false,
    recent: false,
  },
];
