import type { ElementAsset } from "../element.types";
import { svg } from "./svg-helper";

export const BUSINESS_ELEMENTS: readonly ElementAsset[] = [
  {
    id: "business-briefcase",
    name: "Briefcase",
    category: "Business",
    tags: ["work", "office", "bag", "job", "case"],
    svg: svg('<path d="M38 32Q38 14 50 14Q62 14 62 32" fill="none" stroke="#2563eb" stroke-width="5" stroke-linecap="round"/><rect x="10" y="32" width="80" height="54" rx="8" fill="none" stroke="#2563eb" stroke-width="5"/><path d="M10 52H90" stroke="#2563eb" stroke-width="4"/>'),
    defaultSize: { width: 96, height: 86.4 },
    geometryBounds: { x: 10, y: 14, width: 80, height: 72 },
    insertion: { kind: "graphic" },
    colourMode: "fill-and-stroke",
    favourite: false,
    recent: false,
  },
  {
    id: "business-handshake",
    name: "Handshake",
    category: "Business",
    tags: ["deal", "agreement", "partnership", "meeting", "trust"],
    svg: svg('<path d="M8 56 L44 36 L52 44 L18 66Z" fill="none" stroke="#2563eb" stroke-width="5" stroke-linejoin="round"/><path d="M92 56 L56 36 L48 44 L82 66Z" fill="none" stroke="#2563eb" stroke-width="5" stroke-linejoin="round"/>'),
    defaultSize: { width: 120, height: 42.857 },
    geometryBounds: { x: 8, y: 36, width: 84, height: 30 },
    insertion: { kind: "graphic" },
    colourMode: "fill-and-stroke",
    favourite: false,
    recent: false,
  },
  {
    id: "business-growth-chart",
    name: "Growth Chart",
    category: "Business",
    tags: ["growth", "trend", "line chart", "increase", "stats", "analytics"],
    svg: svg('<path d="M8 82H92" fill="none" stroke="#2563eb" stroke-width="5" stroke-linecap="round"/><path d="M10 65L32 50L50 58L74 25L92 10" fill="none" stroke="#2563eb" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/><path d="M80 10H92V22" fill="none" stroke="#2563eb" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/>'),
    defaultSize: { width: 120, height: 102.959 },
    geometryBounds: { x: 8, y: 9.5, width: 84.5, height: 72.5 },
    insertion: { kind: "graphic" },
    favourite: false,
    recent: false,
  },
  {
    id: "business-bar-chart",
    name: "Bar Chart",
    category: "Business",
    tags: ["chart", "statistics", "analytics", "graph", "report"],
    svg: svg('<rect x="12" y="58" width="14" height="30" fill="none" stroke="#2563eb" stroke-width="5"/><rect x="32" y="43" width="14" height="45" fill="none" stroke="#2563eb" stroke-width="5"/><rect x="52" y="63" width="14" height="25" fill="none" stroke="#2563eb" stroke-width="5"/><rect x="72" y="33" width="14" height="55" fill="none" stroke="#2563eb" stroke-width="5"/>'),
    defaultSize: { width: 100, height: 74.324 },
    geometryBounds: { x: 12, y: 33, width: 74, height: 55 },
    maxStrokeWidth: 8,
    insertion: { kind: "graphic" },
    colourMode: "fill-and-stroke",
    favourite: false,
    recent: false,
  },
  {
    id: "business-pie-chart",
    name: "Pie Chart",
    category: "Business",
    tags: ["chart", "statistics", "analytics", "graph", "percentage"],
    svg: svg('<circle cx="50" cy="50" r="38" fill="none" stroke="#2563eb" stroke-width="5"/><path d="M50 50L88 50M50 50L50 12" fill="none" stroke="#2563eb" stroke-width="5" stroke-linecap="round"/>'),
    defaultSize: { width: 96, height: 96 },
    geometryBounds: { x: 12, y: 12, width: 76, height: 76 },
    insertion: { kind: "graphic" },
    colourMode: "fill-and-stroke",
    favourite: false,
    recent: false,
  },
  {
    id: "business-target",
    name: "Target",
    category: "Business",
    tags: ["goal", "aim", "focus", "bullseye", "objective"],
    svg: svg('<circle cx="50" cy="50" r="38" fill="none" stroke="#2563eb" stroke-width="4"/><circle cx="50" cy="50" r="24" fill="none" stroke="#2563eb" stroke-width="4"/><circle cx="50" cy="50" r="8" fill="none" stroke="#2563eb" stroke-width="5"/>'),
    defaultSize: { width: 96, height: 96 },
    geometryBounds: { x: 12, y: 12, width: 76, height: 76 },
    maxStrokeWidth: 10,
    insertion: { kind: "graphic" },
    colourMode: "fill-and-stroke",
    favourite: false,
    recent: false,
  },
  {
    id: "business-calendar",
    name: "Calendar",
    category: "Business",
    tags: ["date", "schedule", "planner", "event", "month"],
    svg: svg('<rect x="10" y="18" width="80" height="72" rx="7" fill="none" stroke="#2563eb" stroke-width="5"/><path d="M28 10V26M72 10V26" stroke="#2563eb" stroke-width="5" stroke-linecap="round"/><path d="M10 34H90" stroke="#2563eb" stroke-width="4"/><path d="M25 50h10M45 50h10M65 50h10M25 65h10M45 65h10M65 65h10" stroke="#2563eb" stroke-width="4" stroke-linecap="round"/>'),
    defaultSize: { width: 100, height: 100 },
    geometryBounds: { x: 10, y: 10, width: 80, height: 80 },
    insertion: { kind: "graphic" },
    colourMode: "fill-and-stroke",
    favourite: false,
    recent: false,
  },
  {
    id: "business-clock",
    name: "Clock",
    category: "Business",
    tags: ["time", "schedule", "deadline", "watch", "hour"],
    svg: svg('<circle cx="50" cy="50" r="38" fill="none" stroke="#2563eb" stroke-width="5"/><path d="M50 50L50 26M50 50L66 60" fill="none" stroke="#2563eb" stroke-width="5" stroke-linecap="round"/>'),
    defaultSize: { width: 96, height: 96 },
    geometryBounds: { x: 12, y: 12, width: 76, height: 76 },
    insertion: { kind: "graphic" },
    colourMode: "fill-and-stroke",
    favourite: false,
    recent: false,
  },
  {
    id: "business-coin-stack",
    name: "Coin Stack",
    category: "Business",
    tags: ["money", "coins", "cash", "savings", "finance"],
    svg: svg('<ellipse cx="50" cy="70" rx="32" ry="10" fill="none" stroke="#2563eb" stroke-width="4"/><ellipse cx="50" cy="58" rx="32" ry="10" fill="none" stroke="#2563eb" stroke-width="4"/><ellipse cx="50" cy="46" rx="32" ry="10" fill="none" stroke="#2563eb" stroke-width="4"/>'),
    defaultSize: { width: 100, height: 68.75 },
    geometryBounds: { x: 18, y: 36, width: 64, height: 44 },
    maxStrokeWidth: 7,
    insertion: { kind: "graphic" },
    colourMode: "fill-and-stroke",
    favourite: false,
    recent: false,
  },
  {
    id: "business-wallet",
    name: "Wallet",
    category: "Business",
    tags: ["money", "cash", "purse", "finance", "payment"],
    svg: svg('<rect x="10" y="28" width="80" height="50" rx="8" fill="none" stroke="#2563eb" stroke-width="5"/><path d="M10 46H90" stroke="#2563eb" stroke-width="4"/><circle cx="78" cy="46" r="5" fill="none" stroke="#2563eb" stroke-width="3"/>'),
    defaultSize: { width: 100, height: 62.5 },
    geometryBounds: { x: 10, y: 28, width: 80, height: 50 },
    insertion: { kind: "graphic" },
    colourMode: "fill-and-stroke",
    favourite: false,
    recent: false,
  },
  {
    id: "business-invoice",
    name: "Invoice",
    category: "Business",
    tags: ["receipt", "bill", "payment", "document", "order"],
    svg: svg('<path d="M15 10H85V68L78 76L71 68L64 76L57 68L50 76L43 68L36 76L29 68L22 76L15 68Z" fill="none" stroke="#2563eb" stroke-width="4" stroke-linejoin="round"/><path d="M25 28H75M25 40H75M25 52H60" stroke="#2563eb" stroke-width="3.5" stroke-linecap="round"/>'),
    defaultSize: { width: 100, height: 94.286 },
    geometryBounds: { x: 15, y: 10, width: 70, height: 66 },
    insertion: { kind: "graphic" },
    colourMode: "fill-and-stroke",
    favourite: false,
    recent: false,
  },
  {
    id: "business-office-building",
    name: "Office Building",
    category: "Business",
    tags: ["building", "company", "workplace", "corporate", "tower"],
    svg: svg('<rect x="30" y="8" width="40" height="84" fill="none" stroke="#2563eb" stroke-width="5"/><path d="M38 18h5v5h-5zM50 18h5v5h-5zM62 18h5v5h-5zM38 32h5v5h-5zM50 32h5v5h-5zM62 32h5v5h-5zM38 46h5v5h-5zM50 46h5v5h-5zM62 46h5v5h-5zM38 60h5v5h-5zM50 60h5v5h-5zM62 60h5v5h-5z" fill="none" stroke="#2563eb" stroke-width="2.5"/>'),
    defaultSize: { width: 46.667, height: 98 },
    geometryBounds: { x: 30, y: 8, width: 40, height: 84 },
    insertion: { kind: "graphic" },
    colourMode: "fill-and-stroke",
    favourite: false,
    recent: false,
  },
  {
    id: "business-id-badge",
    name: "ID Badge",
    category: "Business",
    tags: ["identity", "employee", "pass", "badge", "credential"],
    svg: svg('<rect x="44" y="6" width="12" height="10" rx="2" fill="none" stroke="#2563eb" stroke-width="4"/><rect x="22" y="16" width="56" height="70" rx="8" fill="none" stroke="#2563eb" stroke-width="5"/><circle cx="50" cy="38" r="12" fill="none" stroke="#2563eb" stroke-width="4"/><path d="M32 60H68M32 70H68" stroke="#2563eb" stroke-width="4" stroke-linecap="round"/>'),
    defaultSize: { width: 70.807, height: 100 },
    geometryBounds: { x: 21.5, y: 6, width: 57, height: 80.5 },
    maxStrokeWidth: 10,
    insertion: { kind: "graphic" },
    colourMode: "fill-and-stroke",
    favourite: false,
    recent: false,
  },
  {
    id: "business-contract",
    name: "Contract",
    category: "Business",
    tags: ["document", "agreement", "signature", "legal", "paper"],
    svg: svg('<rect x="18" y="8" width="64" height="84" fill="none" stroke="#2563eb" stroke-width="5"/><path d="M28 26H72M28 38H72M28 50H62" stroke="#2563eb" stroke-width="4" stroke-linecap="round"/><path d="M28 70Q34 62 40 70T52 70T64 70" fill="none" stroke="#2563eb" stroke-width="4" stroke-linecap="round"/>'),
    defaultSize: { width: 76.19, height: 100 },
    geometryBounds: { x: 18, y: 8, width: 64, height: 84 },
    insertion: { kind: "graphic" },
    colourMode: "fill-and-stroke",
    favourite: false,
    recent: false,
  },
  {
    id: "business-presentation-board",
    name: "Presentation Board",
    category: "Business",
    tags: ["presentation", "easel", "meeting", "chart", "pitch"],
    svg: svg('<path d="M30 90L42 50M70 90L58 50" fill="none" stroke="#2563eb" stroke-width="4" stroke-linecap="round"/><rect x="22" y="10" width="56" height="42" fill="none" stroke="#2563eb" stroke-width="5"/><path d="M32 44V30M46 44V22M60 44V34" stroke="#2563eb" stroke-width="4" stroke-linecap="round"/>'),
    defaultSize: { width: 101.156, height: 142.86 },
    geometryBounds: { x: 21.5, y: 9.5, width: 57, height: 80.5 },
    insertion: { kind: "graphic" },
    colourMode: "fill-and-stroke",
    favourite: false,
    recent: false,
  },
];
