import type { ElementAsset } from "../element.types";
import { svg } from "./svg-helper";

export const LINES_AND_ARROWS_ELEMENTS: readonly ElementAsset[] = [
  {
    id: "line-straight",
    name: "Line",
    category: "Lines and arrows",
    tags: ["divider", "rule", "straight", "stroke", "border"],
    svg: svg('<path d="M5 50H95" fill="none" stroke="#2563eb" stroke-width="8" stroke-linecap="round"/>'),
    defaultSize: { width: 140, height: 3.04 },
    geometryBounds: { x: 5, y: 50, width: 90, height: 0 },
    insertion: { kind: "shape", shapeKind: "line" },
    favourite: false,
    recent: false,
  },
  {
    id: "line-dashed",
    name: "Dashed Line",
    category: "Lines and arrows",
    tags: ["dash", "divider", "separator", "dotted", "border"],
    svg: svg('<path d="M5 50H95" fill="none" stroke="#2563eb" stroke-width="8" stroke-dasharray="14 10" stroke-linecap="round"/>'),
    defaultSize: { width: 140, height: 11.43 },
    geometryBounds: { x: 5, y: 50, width: 90, height: 0 },
    insertion: { kind: "graphic" },
    favourite: false,
    recent: false,
  },
  {
    id: "arrow-right",
    name: "Arrow",
    category: "Lines and arrows",
    tags: ["direction", "pointer", "right", "next", "forward"],
    svg: svg('<path d="M7 50H84M62 27l23 23-23 23" fill="none" stroke="#2563eb" stroke-width="9" stroke-linecap="round" stroke-linejoin="round"/>'),
    defaultSize: { width: 140, height: 84 },
    geometryBounds: { x: 7, y: 27, width: 78, height: 46 },
    insertion: { kind: "shape", shapeKind: "arrow" },
    favourite: false,
    recent: false,
  },
  {
    id: "arrow-double",
    name: "Double Arrow",
    category: "Lines and arrows",
    tags: ["both sides", "expand", "width", "pointer", "swap"],
    svg: svg('<path d="M18 50h64M38 27L16 50l22 23M62 27l22 23-22 23" fill="none" stroke="#2563eb" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>'),
    defaultSize: { width: 140, height: 99.47 },
    geometryBounds: { x: 16, y: 27, width: 68, height: 46 },
    insertion: { kind: "graphic" },
    favourite: false,
    recent: false,
  },
  {
    id: "arrow-curved",
    name: "Curved Arrow",
    category: "Lines and arrows",
    tags: ["turn", "rotate", "u-turn", "curve", "loop"],
    svg: svg('<path d="M15 82C15 38 38 18 80 18M58 5l25 13-25 15" fill="none" stroke="#2563eb" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>'),
    defaultSize: { width: 98.35, height: 110 },
    geometryBounds: { x: 15, y: 5, width: 68, height: 77 },
    insertion: { kind: "graphic" },
    favourite: false,
    recent: false,
  },
];
