import type { Template, TemplateCategory } from "./templates.types";

export const TEMPLATES_CATALOG: readonly Template[] = [
  {
    id: "minimal-product-badge",
    name: "Minimalist Product Badge",
    category: "product",
    description: "Sleek promo badge with high contrast for digital products and discounts.",
    presetId: "square",
    width: 360,
    height: 360,
    badge: "Popular",
    tags: ["badge", "product", "discount", "promo", "square", "minimal"],
    backgroundColor: "#0f172a",
    items: [
      {
        id: "bg-card",
        type: "shape",
        shapeKind: "roundedRectangle",
        hidden: false,
        locked: false,
        position: { x: 20, y: 20 },
        size: { width: 320, height: 320 },
        rotation: 0,
        fill: "#1e293b",
        stroke: "#38bdf8",
        strokeWidth: 2,
      },
      {
        id: "badge-circle",
        type: "shape",
        shapeKind: "circle",
        hidden: false,
        locked: false,
        position: { x: 140, y: 50 },
        size: { width: 80, height: 80 },
        rotation: 0,
        fill: "#0284c7",
        stroke: "#000000",
        strokeWidth: 0,
      },
      {
        id: "badge-text",
        type: "text",
        hidden: false,
        locked: false,
        value: "50%\nOFF",
        position: { x: 160, y: 68 },
        fontSize: 18,
        color: "#ffffff",
        fontFamily: "Impact",
        rotation: 0,
      },
      {
        id: "main-title",
        type: "text",
        hidden: false,
        locked: false,
        value: "DIGITAL ASSET PACK",
        position: { x: 45, y: 160 },
        fontSize: 22,
        color: "#f8fafc",
        fontFamily: "Trebuchet MS",
        rotation: 0,
      },
      {
        id: "subtext",
        type: "text",
        hidden: false,
        locked: false,
        value: "Premium UI Components & Templates",
        position: { x: 60, y: 210 },
        fontSize: 14,
        color: "#94a3b8",
        fontFamily: "Arial",
        rotation: 0,
      },
      {
        id: "cta-btn",
        type: "shape",
        shapeKind: "roundedRectangle",
        hidden: false,
        locked: false,
        position: { x: 100, y: 260 },
        size: { width: 160, height: 44 },
        rotation: 0,
        fill: "#38bdf8",
        stroke: "#000000",
        strokeWidth: 0,
      },
      {
        id: "cta-text",
        type: "text",
        hidden: false,
        locked: false,
        value: "GET IT NOW",
        position: { x: 135, y: 273 },
        fontSize: 14,
        color: "#0f172a",
        fontFamily: "Arial",
        rotation: 0,
      },
    ],
  },
  {
    id: "inspirational-quote-card",
    name: "Inspirational Quote Card",
    category: "social",
    description: "Elegant quote layout ideal for Instagram, LinkedIn, and social feeds.",
    presetId: "instagram-post",
    width: 1080,
    height: 1080,
    badge: "Trending",
    tags: ["quote", "instagram", "social", "minimal", "typography"],
    backgroundColor: "#111827",
    items: [
      {
        id: "frame",
        type: "shape",
        shapeKind: "roundedRectangle",
        hidden: false,
        locked: false,
        position: { x: 60, y: 60 },
        size: { width: 960, height: 960 },
        rotation: 0,
        fill: "#1f2937",
        stroke: "#374151",
        strokeWidth: 3,
      },
      {
        id: "quote-icon",
        type: "text",
        hidden: false,
        locked: false,
        value: "“",
        position: { x: 120, y: 120 },
        fontSize: 160,
        color: "#38bdf8",
        fontFamily: "Georgia",
        rotation: 0,
      },
      {
        id: "quote-body",
        type: "text",
        hidden: false,
        locked: false,
        value: "Creativity is intelligence having fun.",
        position: { x: 140, y: 380 },
        fontSize: 56,
        color: "#f9fafb",
        fontFamily: "Georgia",
        rotation: 0,
      },
      {
        id: "divider",
        type: "shape",
        shapeKind: "line",
        hidden: false,
        locked: false,
        position: { x: 140, y: 640 },
        size: { width: 180, height: 4 },
        rotation: 0,
        fill: null,
        stroke: "#38bdf8",
        strokeWidth: 4,
      },
      {
        id: "author",
        type: "text",
        hidden: false,
        locked: false,
        value: "— ALBERT EINSTEIN",
        position: { x: 140, y: 680 },
        fontSize: 28,
        color: "#9ca3af",
        fontFamily: "Trebuchet MS",
        rotation: 0,
      },
    ],
  },
  {
    id: "ebook-masterclass-cover",
    name: "Ebook Masterclass Cover",
    category: "product",
    description: "Professional digital guide and ebook cover layout.",
    presetId: "portrait",
    width: 360,
    height: 480,
    badge: "Pro",
    tags: ["ebook", "cover", "product", "guide", "digital"],
    backgroundColor: "#0f172a",
    items: [
      {
        id: "bg-shape",
        type: "shape",
        shapeKind: "rectangle",
        hidden: false,
        locked: false,
        position: { x: 0, y: 0 },
        size: { width: 360, height: 480 },
        rotation: 0,
        fill: "#0f172a",
        stroke: "#1e293b",
        strokeWidth: 1,
      },
      {
        id: "top-pill",
        type: "shape",
        shapeKind: "roundedRectangle",
        hidden: false,
        locked: false,
        position: { x: 30, y: 35 },
        size: { width: 140, height: 28 },
        rotation: 0,
        fill: "#0369a1",
        stroke: "#000000",
        strokeWidth: 0,
      },
      {
        id: "top-pill-text",
        type: "text",
        hidden: false,
        locked: false,
        value: "CREATOR GUIDE",
        position: { x: 45, y: 41 },
        fontSize: 11,
        color: "#ffffff",
        fontFamily: "Trebuchet MS",
        rotation: 0,
      },
      {
        id: "title-main",
        type: "text",
        hidden: false,
        locked: false,
        value: "BUILD & SELL\nDIGITAL PRODUCTS",
        position: { x: 30, y: 100 },
        fontSize: 26,
        color: "#ffffff",
        fontFamily: "Impact",
        rotation: 0,
      },
      {
        id: "star-accent",
        type: "shape",
        shapeKind: "star",
        hidden: false,
        locked: false,
        position: { x: 290, y: 105 },
        size: { width: 35, height: 35 },
        rotation: 12,
        fill: "#facc15",
        stroke: "#000000",
        strokeWidth: 0,
      },
      {
        id: "subtitle",
        type: "text",
        hidden: false,
        locked: false,
        value: "The complete roadmap for modern online creators.",
        position: { x: 30, y: 190 },
        fontSize: 13,
        color: "#94a3b8",
        fontFamily: "Arial",
        rotation: 0,
      },
      {
        id: "bottom-bar",
        type: "shape",
        shapeKind: "rectangle",
        hidden: false,
        locked: false,
        position: { x: 0, y: 400 },
        size: { width: 360, height: 80 },
        rotation: 0,
        fill: "#1e293b",
        stroke: "#334155",
        strokeWidth: 1,
      },
      {
        id: "author-text",
        type: "text",
        hidden: false,
        locked: false,
        value: "BY GRIPIX STUDIO • 2026 EDITION",
        position: { x: 30, y: 430 },
        fontSize: 12,
        color: "#38bdf8",
        fontFamily: "Trebuchet MS",
        rotation: 0,
      },
    ],
  },
  {
    id: "flash-sale-banner",
    name: "Flash Sale Banner",
    category: "marketing",
    description: "Eye-catching promo graphic for limited-time offers and storefront sales.",
    presetId: "landscape",
    width: 360,
    height: 256,
    badge: "Sale",
    tags: ["sale", "banner", "marketing", "promo", "landscape"],
    backgroundColor: "#450a0a",
    items: [
      {
        id: "sale-bg",
        type: "shape",
        shapeKind: "roundedRectangle",
        hidden: false,
        locked: false,
        position: { x: 10, y: 10 },
        size: { width: 340, height: 236 },
        rotation: 0,
        fill: "#7f1d1d",
        stroke: "#ef4444",
        strokeWidth: 2,
      },
      {
        id: "star-badge",
        type: "shape",
        shapeKind: "star",
        hidden: false,
        locked: false,
        position: { x: 25, y: 25 },
        size: { width: 50, height: 50 },
        rotation: 0,
        fill: "#facc15",
        stroke: "#000000",
        strokeWidth: 0,
      },
      {
        id: "sale-header",
        type: "text",
        hidden: false,
        locked: false,
        value: "24-HOUR FLASH SALE",
        position: { x: 85, y: 35 },
        fontSize: 20,
        color: "#facc15",
        fontFamily: "Impact",
        rotation: 0,
      },
      {
        id: "discount-main",
        type: "text",
        hidden: false,
        locked: false,
        value: "UP TO 70% OFF",
        position: { x: 40, y: 100 },
        fontSize: 32,
        color: "#ffffff",
        fontFamily: "Impact",
        rotation: 0,
      },
      {
        id: "sub-details",
        type: "text",
        hidden: false,
        locked: false,
        value: "All digital templates & courses included",
        position: { x: 40, y: 155 },
        fontSize: 12,
        color: "#fca5a5",
        fontFamily: "Arial",
        rotation: 0,
      },
      {
        id: "shop-btn",
        type: "shape",
        shapeKind: "roundedRectangle",
        hidden: false,
        locked: false,
        position: { x: 40, y: 185 },
        size: { width: 140, height: 36 },
        rotation: 0,
        fill: "#facc15",
        stroke: "#000000",
        strokeWidth: 0,
      },
      {
        id: "shop-btn-text",
        type: "text",
        hidden: false,
        locked: false,
        value: "SHOP NOW ›",
        position: { x: 75, y: 195 },
        fontSize: 13,
        color: "#7f1d1d",
        fontFamily: "Impact",
        rotation: 0,
      },
    ],
  },
  {
    id: "podcast-episode-card",
    name: "Podcast Episode Card",
    category: "social",
    description: "Modern podcast graphic featuring episode numbers and title highlights.",
    presetId: "instagram-post",
    width: 1080,
    height: 1080,
    tags: ["podcast", "social", "instagram", "media", "audio"],
    backgroundColor: "#030712",
    items: [
      {
        id: "main-card",
        type: "shape",
        shapeKind: "roundedRectangle",
        hidden: false,
        locked: false,
        position: { x: 80, y: 80 },
        size: { width: 920, height: 920 },
        rotation: 0,
        fill: "#111827",
        stroke: "#1f2937",
        strokeWidth: 2,
      },
      {
        id: "ep-pill",
        type: "shape",
        shapeKind: "roundedRectangle",
        hidden: false,
        locked: false,
        position: { x: 140, y: 150 },
        size: { width: 260, height: 60 },
        rotation: 0,
        fill: "#2563eb",
        stroke: "#000000",
        strokeWidth: 0,
      },
      {
        id: "ep-text",
        type: "text",
        hidden: false,
        locked: false,
        value: "NEW EPISODE #42",
        position: { x: 170, y: 165 },
        fontSize: 22,
        color: "#ffffff",
        fontFamily: "Trebuchet MS",
        rotation: 0,
      },
      {
        id: "pod-title",
        type: "text",
        hidden: false,
        locked: false,
        value: "THE CREATOR ECONOMY\nIN 2026",
        position: { x: 140, y: 280 },
        fontSize: 52,
        color: "#38bdf8",
        fontFamily: "Trebuchet MS",
        rotation: 0,
      },
      {
        id: "pod-sub",
        type: "text",
        hidden: false,
        locked: false,
        value: "How independent creators scale digital products without ad spend.",
        position: { x: 140, y: 520 },
        fontSize: 28,
        color: "#9ca3af",
        fontFamily: "Arial",
        rotation: 0,
      },
      {
        id: "host-info",
        type: "text",
        hidden: false,
        locked: false,
        value: "HOST: ALEX RIVER • AVAILABLE ON ALL PLATFORMS",
        position: { x: 140, y: 800 },
        fontSize: 22,
        color: "#6b7280",
        fontFamily: "Arial",
        rotation: 0,
      },
    ],
  },
  {
    id: "modern-minimal-logo",
    name: "Modern Minimal Logo",
    category: "personal",
    description: "Clean vector mark and typography logo preset for brands and creators.",
    presetId: "square",
    width: 360,
    height: 360,
    badge: "New",
    tags: ["logo", "branding", "minimal", "vector", "square"],
    backgroundColor: "#090d16",
    items: [
      {
        id: "center-shape",
        type: "shape",
        shapeKind: "star",
        hidden: false,
        locked: false,
        position: { x: 140, y: 80 },
        size: { width: 80, height: 80 },
        rotation: 45,
        fill: null,
        stroke: "#38bdf8",
        strokeWidth: 4,
      },
      {
        id: "brand-name",
        type: "text",
        hidden: false,
        locked: false,
        value: "AURA LABS",
        position: { x: 80, y: 200 },
        fontSize: 28,
        color: "#f8fafc",
        fontFamily: "Trebuchet MS",
        rotation: 0,
      },
      {
        id: "brand-tagline",
        type: "text",
        hidden: false,
        locked: false,
        value: "DIGITAL DESIGN STUDIO",
        position: { x: 100, y: 250 },
        fontSize: 12,
        color: "#64748b",
        fontFamily: "Arial",
        rotation: 0,
      },
    ],
  },
  {
    id: "instagram-story-promo",
    name: "Instagram Story Promo",
    category: "social",
    description: "Vertical story template engineered for high swipe-through engagement.",
    presetId: "instagram-story",
    width: 1080,
    height: 1920,
    tags: ["story", "instagram", "mobile", "promo", "social"],
    backgroundColor: "#030712",
    items: [
      {
        id: "story-card",
        type: "shape",
        shapeKind: "roundedRectangle",
        hidden: false,
        locked: false,
        position: { x: 60, y: 100 },
        size: { width: 960, height: 1720 },
        rotation: 0,
        fill: "#111827",
        stroke: "#1f2937",
        strokeWidth: 3,
      },
      {
        id: "top-tag",
        type: "text",
        hidden: false,
        locked: false,
        value: "✦ NEW RELEASE",
        position: { x: 120, y: 200 },
        fontSize: 32,
        color: "#38bdf8",
        fontFamily: "Trebuchet MS",
        rotation: 0,
      },
      {
        id: "main-headline",
        type: "text",
        hidden: false,
        locked: false,
        value: "LAUNCH YOUR\nFIRST COURSE",
        position: { x: 120, y: 340 },
        fontSize: 72,
        color: "#ffffff",
        fontFamily: "Impact",
        rotation: 0,
      },
      {
        id: "feature-1-box",
        type: "shape",
        shapeKind: "roundedRectangle",
        hidden: false,
        locked: false,
        position: { x: 120, y: 680 },
        size: { width: 840, height: 120 },
        rotation: 0,
        fill: "#1f2937",
        stroke: "#374151",
        strokeWidth: 2,
      },
      {
        id: "feature-1-text",
        type: "text",
        hidden: false,
        locked: false,
        value: "✓ Step-by-Step Curriculum Templates",
        position: { x: 160, y: 720 },
        fontSize: 32,
        color: "#e5e7eb",
        fontFamily: "Arial",
        rotation: 0,
      },
      {
        id: "feature-2-box",
        type: "shape",
        shapeKind: "roundedRectangle",
        hidden: false,
        locked: false,
        position: { x: 120, y: 840 },
        size: { width: 840, height: 120 },
        rotation: 0,
        fill: "#1f2937",
        stroke: "#374151",
        strokeWidth: 2,
      },
      {
        id: "feature-2-text",
        type: "text",
        hidden: false,
        locked: false,
        value: "✓ High-Converting Sales Page Wireframes",
        position: { x: 160, y: 880 },
        fontSize: 32,
        color: "#e5e7eb",
        fontFamily: "Arial",
        rotation: 0,
      },
      {
        id: "cta-bottom-btn",
        type: "shape",
        shapeKind: "roundedRectangle",
        hidden: false,
        locked: false,
        position: { x: 120, y: 1550 },
        size: { width: 840, height: 140 },
        rotation: 0,
        fill: "#38bdf8",
        stroke: "#000000",
        strokeWidth: 0,
      },
      {
        id: "cta-bottom-text",
        type: "text",
        hidden: false,
        locked: false,
        value: "SWIPE UP TO GET STARTED",
        position: { x: 260, y: 1600 },
        fontSize: 34,
        color: "#030712",
        fontFamily: "Impact",
        rotation: 0,
      },
    ],
  },
  {
    id: "course-certificate-header",
    name: "Course Certificate Header",
    category: "product",
    description: "Formal completion certificate header for digital courses and workshops.",
    presetId: "a4-landscape",
    width: 1123,
    height: 794,
    tags: ["certificate", "print", "landscape", "education", "formal"],
    backgroundColor: "#020617",
    items: [
      {
        id: "outer-border",
        type: "shape",
        shapeKind: "rectangle",
        hidden: false,
        locked: false,
        position: { x: 40, y: 40 },
        size: { width: 1043, height: 714 },
        rotation: 0,
        fill: "#0f172a",
        stroke: "#eab308",
        strokeWidth: 4,
      },
      {
        id: "inner-border",
        type: "shape",
        shapeKind: "rectangle",
        hidden: false,
        locked: false,
        position: { x: 60, y: 60 },
        size: { width: 1003, height: 674 },
        rotation: 0,
        fill: null,
        stroke: "#334155",
        strokeWidth: 1,
      },
      {
        id: "cert-header",
        type: "text",
        hidden: false,
        locked: false,
        value: "CERTIFICATE OF COMPLETION",
        position: { x: 220, y: 150 },
        fontSize: 48,
        color: "#facc15",
        fontFamily: "Georgia",
        rotation: 0,
      },
      {
        id: "cert-sub",
        type: "text",
        hidden: false,
        locked: false,
        value: "THIS IS PROUDLY PRESENTED TO",
        position: { x: 380, y: 240 },
        fontSize: 24,
        color: "#94a3b8",
        fontFamily: "Trebuchet MS",
        rotation: 0,
      },
      {
        id: "recipient-name",
        type: "text",
        hidden: false,
        locked: false,
        value: "ALEXANDER MORGAN",
        position: { x: 300, y: 320 },
        fontSize: 44,
        color: "#ffffff",
        fontFamily: "Georgia",
        rotation: 0,
      },
      {
        id: "line-name",
        type: "shape",
        shapeKind: "line",
        hidden: false,
        locked: false,
        position: { x: 260, y: 400 },
        size: { width: 603, height: 2 },
        rotation: 0,
        fill: null,
        stroke: "#eab308",
        strokeWidth: 2,
      },
      {
        id: "cert-reason",
        type: "text",
        hidden: false,
        locked: false,
        value: "For successfully completing the Masterclass in Digital Product Design.",
        position: { x: 240, y: 450 },
        fontSize: 22,
        color: "#cbd5e1",
        fontFamily: "Arial",
        rotation: 0,
      },
    ],
  },
  {
    id: "event-webinar-invite",
    name: "Event Webinar Invite",
    category: "marketing",
    description: "Landscape banner for online masterclasses, podcasts, and live events.",
    presetId: "facebook-post",
    width: 1200,
    height: 630,
    tags: ["webinar", "event", "facebook", "marketing", "banner"],
    backgroundColor: "#0b1329",
    items: [
      {
        id: "webinar-card",
        type: "shape",
        shapeKind: "roundedRectangle",
        hidden: false,
        locked: false,
        position: { x: 40, y: 40 },
        size: { width: 1120, height: 550 },
        rotation: 0,
        fill: "#1e293b",
        stroke: "#38bdf8",
        strokeWidth: 2,
      },
      {
        id: "tag-pill",
        type: "shape",
        shapeKind: "roundedRectangle",
        hidden: false,
        locked: false,
        position: { x: 90, y: 90 },
        size: { width: 180, height: 40 },
        rotation: 0,
        fill: "#0284c7",
        stroke: "#000000",
        strokeWidth: 0,
      },
      {
        id: "tag-text",
        type: "text",
        hidden: false,
        locked: false,
        value: "LIVE WEBINAR",
        position: { x: 120, y: 101 },
        fontSize: 14,
        color: "#ffffff",
        fontFamily: "Trebuchet MS",
        rotation: 0,
      },
      {
        id: "webinar-title",
        type: "text",
        hidden: false,
        locked: false,
        value: "DESIGN SYSTEMS THAT SCALE",
        position: { x: 90, y: 170 },
        fontSize: 44,
        color: "#f8fafc",
        fontFamily: "Trebuchet MS",
        rotation: 0,
      },
      {
        id: "webinar-details",
        type: "text",
        hidden: false,
        locked: false,
        value: "THURSDAY, AUGUST 15 • 6:00 PM EST",
        position: { x: 90, y: 260 },
        fontSize: 24,
        color: "#38bdf8",
        fontFamily: "Arial",
        rotation: 0,
      },
      {
        id: "speaker-info",
        type: "text",
        hidden: false,
        locked: false,
        value: "Featuring lead design engineers from Gripix Studio",
        position: { x: 90, y: 320 },
        fontSize: 18,
        color: "#94a3b8",
        fontFamily: "Arial",
        rotation: 0,
      },
      {
        id: "register-btn",
        type: "shape",
        shapeKind: "roundedRectangle",
        hidden: false,
        locked: false,
        position: { x: 90, y: 400 },
        size: { width: 220, height: 50 },
        rotation: 0,
        fill: "#38bdf8",
        stroke: "#000000",
        strokeWidth: 0,
      },
      {
        id: "register-text",
        type: "text",
        hidden: false,
        locked: false,
        value: "RESERVE SEAT",
        position: { x: 135, y: 415 },
        fontSize: 16,
        color: "#0f172a",
        fontFamily: "Impact",
        rotation: 0,
      },
    ],
  },
  {
    id: "etsy-product-mockup",
    name: "Etsy Product Mockup Frame",
    category: "product",
    description: "High-resolution 2000x2000 product listing template for Etsy storefronts.",
    presetId: "etsy-listing",
    width: 2000,
    height: 2000,
    tags: ["etsy", "listing", "product", "mockup", "store"],
    backgroundColor: "#020617",
    items: [
      {
        id: "mockup-bg",
        type: "shape",
        shapeKind: "roundedRectangle",
        hidden: false,
        locked: false,
        position: { x: 100, y: 100 },
        size: { width: 1800, height: 1800 },
        rotation: 0,
        fill: "#0f172a",
        stroke: "#38bdf8",
        strokeWidth: 4,
      },
      {
        id: "top-label",
        type: "text",
        hidden: false,
        locked: false,
        value: "INSTANT DIGITAL DOWNLOAD",
        position: { x: 450, y: 220 },
        fontSize: 64,
        color: "#facc15",
        fontFamily: "Impact",
        rotation: 0,
      },
      {
        id: "center-preview-card",
        type: "shape",
        shapeKind: "roundedRectangle",
        hidden: false,
        locked: false,
        position: { x: 300, y: 380 },
        size: { width: 1400, height: 1000 },
        rotation: 0,
        fill: "#1e293b",
        stroke: "#334155",
        strokeWidth: 3,
      },
      {
        id: "preview-text",
        type: "text",
        hidden: false,
        locked: false,
        value: "YOUR PRODUCT DESIGN MOCKUP HERE",
        position: { x: 440, y: 840 },
        fontSize: 48,
        color: "#64748b",
        fontFamily: "Trebuchet MS",
        rotation: 0,
      },
      {
        id: "feature-bullet-1",
        type: "text",
        hidden: false,
        locked: false,
        value: "✓ Includes PDF & High-Res PNG Formats",
        position: { x: 300, y: 1460 },
        fontSize: 42,
        color: "#e2e8f0",
        fontFamily: "Arial",
        rotation: 0,
      },
      {
        id: "feature-bullet-2",
        type: "text",
        hidden: false,
        locked: false,
        value: "✓ 100% Customizable in Gripix Editor",
        position: { x: 300, y: 1560 },
        fontSize: 42,
        color: "#e2e8f0",
        fontFamily: "Arial",
        rotation: 0,
      },
    ],
  },
  {
    id: "pinterest-pin-infographic",
    name: "Pinterest Pin Infographic",
    category: "social",
    description: "Vertical Pinterest graphic formatted to drive organic search traffic.",
    presetId: "pinterest-pin",
    width: 1000,
    height: 1500,
    tags: ["pinterest", "pin", "infographic", "social", "vertical"],
    backgroundColor: "#111827",
    items: [
      {
        id: "pin-card",
        type: "shape",
        shapeKind: "roundedRectangle",
        hidden: false,
        locked: false,
        position: { x: 50, y: 50 },
        size: { width: 900, height: 1400 },
        rotation: 0,
        fill: "#1f2937",
        stroke: "#374151",
        strokeWidth: 2,
      },
      {
        id: "pin-header",
        type: "text",
        hidden: false,
        locked: false,
        value: "5 STEPS TO SELL\nDIGITAL PRODUCTS",
        position: { x: 120, y: 120 },
        fontSize: 56,
        color: "#f8fafc",
        fontFamily: "Trebuchet MS",
        rotation: 0,
      },
      {
        id: "step-1-num",
        type: "shape",
        shapeKind: "circle",
        hidden: false,
        locked: false,
        position: { x: 120, y: 380 },
        size: { width: 80, height: 80 },
        rotation: 0,
        fill: "#38bdf8",
        stroke: "#000000",
        strokeWidth: 0,
      },
      {
        id: "step-1-text",
        type: "text",
        hidden: false,
        locked: false,
        value: "1",
        position: { x: 150, y: 395 },
        fontSize: 36,
        color: "#0f172a",
        fontFamily: "Impact",
        rotation: 0,
      },
      {
        id: "step-1-desc",
        type: "text",
        hidden: false,
        locked: false,
        value: "Choose a focused creator niche",
        position: { x: 230, y: 405 },
        fontSize: 28,
        color: "#e5e7eb",
        fontFamily: "Arial",
        rotation: 0,
      },
      {
        id: "step-2-num",
        type: "shape",
        shapeKind: "circle",
        hidden: false,
        locked: false,
        position: { x: 120, y: 520 },
        size: { width: 80, height: 80 },
        rotation: 0,
        fill: "#38bdf8",
        stroke: "#000000",
        strokeWidth: 0,
      },
      {
        id: "step-2-text",
        type: "text",
        hidden: false,
        locked: false,
        value: "2",
        position: { x: 150, y: 535 },
        fontSize: 36,
        color: "#0f172a",
        fontFamily: "Impact",
        rotation: 0,
      },
      {
        id: "step-2-desc",
        type: "text",
        hidden: false,
        locked: false,
        value: "Design templates in Gripix Editor",
        position: { x: 230, y: 545 },
        fontSize: 28,
        color: "#e5e7eb",
        fontFamily: "Arial",
        rotation: 0,
      },
      {
        id: "step-3-num",
        type: "shape",
        shapeKind: "circle",
        hidden: false,
        locked: false,
        position: { x: 120, y: 660 },
        size: { width: 80, height: 80 },
        rotation: 0,
        fill: "#38bdf8",
        stroke: "#000000",
        strokeWidth: 0,
      },
      {
        id: "step-3-text",
        type: "text",
        hidden: false,
        locked: false,
        value: "3",
        position: { x: 150, y: 675 },
        fontSize: 36,
        color: "#0f172a",
        fontFamily: "Impact",
        rotation: 0,
      },
      {
        id: "step-3-desc",
        type: "text",
        hidden: false,
        locked: false,
        value: "Export high-resolution PDF assets",
        position: { x: 230, y: 685 },
        fontSize: 28,
        color: "#e5e7eb",
        fontFamily: "Arial",
        rotation: 0,
      },
      {
        id: "footer-brand",
        type: "text",
        hidden: false,
        locked: false,
        value: "gripixtemplates.com",
        position: { x: 330, y: 1320 },
        fontSize: 24,
        color: "#9ca3af",
        fontFamily: "Trebuchet MS",
        rotation: 0,
      },
    ],
  },
  {
    id: "youtube-thumbnail-starter",
    name: "YouTube Thumbnail Starter",
    category: "marketing",
    description: "High-contrast 16:9 thumbnail template designed for high click-through rates.",
    presetId: "youtube-thumbnail",
    width: 1280,
    height: 720,
    tags: ["youtube", "thumbnail", "video", "marketing", "landscape"],
    backgroundColor: "#030712",
    items: [
      {
        id: "accent-box",
        type: "shape",
        shapeKind: "roundedRectangle",
        hidden: false,
        locked: false,
        position: { x: 50, y: 50 },
        size: { width: 1180, height: 620 },
        rotation: 0,
        fill: "#111827",
        stroke: "#facc15",
        strokeWidth: 3,
      },
      {
        id: "yt-title-1",
        type: "text",
        hidden: false,
        locked: false,
        value: "MAKE $10K/MONTH",
        position: { x: 100, y: 120 },
        fontSize: 72,
        color: "#facc15",
        fontFamily: "Impact",
        rotation: 0,
      },
      {
        id: "yt-title-2",
        type: "text",
        hidden: false,
        locked: false,
        value: "SELLING DIGITAL PRODUCTS",
        position: { x: 100, y: 240 },
        fontSize: 64,
        color: "#ffffff",
        fontFamily: "Impact",
        rotation: 0,
      },
      {
        id: "yt-subtitle",
        type: "text",
        hidden: false,
        locked: false,
        value: "(NO CODING OR EXPERIENCE REQUIRED)",
        position: { x: 100, y: 380 },
        fontSize: 32,
        color: "#38bdf8",
        fontFamily: "Trebuchet MS",
        rotation: 0,
      },
      {
        id: "badge-tag-yt",
        type: "shape",
        shapeKind: "roundedRectangle",
        hidden: false,
        locked: false,
        position: { x: 100, y: 490 },
        size: { width: 280, height: 80 },
        rotation: 0,
        fill: "#ef4444",
        stroke: "#000000",
        strokeWidth: 0,
      },
      {
        id: "badge-text-yt",
        type: "text",
        hidden: false,
        locked: false,
        value: "MUST WATCH!",
        position: { x: 140, y: 512 },
        fontSize: 32,
        color: "#ffffff",
        fontFamily: "Impact",
        rotation: 0,
      },
    ],
  },
];

export const filterTemplates = (
  query: string,
  category: TemplateCategory = "all"
): Template[] => {
  const normalizedQuery = query.trim().toLocaleLowerCase();

  return TEMPLATES_CATALOG.filter((template) => {
    const matchesCategory =
      category === "all" || template.category === category;

    if (!matchesCategory) return false;
    if (!normalizedQuery) return true;

    const searchableText = `${template.name} ${template.description} ${template.category} ${template.tags.join(" ")}`.toLocaleLowerCase();
    return searchableText.includes(normalizedQuery);
  });
};
